name: Generate Modern Violet Defconfig

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout kernel
        uses: actions/checkout@v4
        with:
          ref: hawki
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git bc bison flex libssl-dev \
            make libelf-dev libncurses-dev \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            python3

      - name: Generate base config
        run: |
          mkdir -p out

          make O=out ARCH=arm64 defconfig

      - name: Merge Violet config
        run: |
          ./scripts/kconfig/merge_config.sh \
            -O out \
            out/.config \
            arch/arm64/configs/vendor/violet.config

      - name: Resolve config
        run: |
          make O=out ARCH=arm64 olddefconfig

      - name: Save modern Violet defconfig
        run: |
          make O=out ARCH=arm64 savedefconfig
          cp out/defconfig \
            violet-perf_defconfig

      - name: Upload Violet defconfig
        uses: actions/upload-artifact@v4
        with:
          name: modern-violet-defconfig
          path: violet-perf_defconfig
