name: Test Hawki

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: hawki

      - name: Test
        run: |
          echo "HAWKI WORKFLOW STARTED"
          git branch --show-current
          git rev-parse HEAD
